# -*- coding: utf-8 -*-
"""UNDP - SDG  (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R6QbMg9gIG1IwtoTeyniuda_8Gqy1WuP
"""

import requests
inport os
import json

indicator_series=['SI.POV.DDAY', 'SI.POV.LMIC.GP', 'SI.POV.UMIC', 'SI.POV.MDIM', 'SI.POV.MDIM.XQ', 'SI.POV.NAHC']
country_codes=['KAZ','KGZ','TJK','TKM','UZB']
r=requests.get('http://api.worldbank.org/v2/country/{0}/indicator/{1}?format=json'.format(country_codes[4],indicator_series[1]))
pages=r.json()[0]['pages']
print(pages)

"""
{'indicator': {'id': 'SI.POV.DDAY',
    'value': 'Poverty headcount ratio at $2.15 a day (2017 PPP) (% of population)'},
   'country': {'id': 'KZ', 'value': 'Kazakhstan'},
   'countryiso3code': 'KAZ',
   'date': '1972',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1}
"""

parent=os.getcwd()
directory='SDG-DATA'
path = os.path.join(parent, directory)

# code to prevent server from Connection reset 10054 error
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0",
    "Accept-Encoding": "*",
    "Connection": "keep-alive"
}

for country in countries:
    #send request to grab number of pages for the data
    for indicator in indicator_series:
        req=requests.get('http://api.worldbank.org/v2/country/{0}/indicator/{1}?format=json'.format(country,indicator),headers=headers)
        pages=req.json()[0]['pages']
        #retrieve data for each page separately
        for page in range(pages):
            page=page+1
            r=requests.get('http://api.worldbank.org/v2/country/{0}/indicator/{1}?format=json&page={2}'.format(country,indicator,page),headers=headers)
            data=r.json()[1]
            file=os.path.join(path,"Data_{0}_{1}_page_{2}.json".format(country,indicator,page))
            with open(file, "w") as outfile:
                json.dump(data, outfile)
#             out_file = open("{0}_{1}_{2}.json".format(country,indicator,page), "w")
            out_file.close()

#opening sample json
# Opening JSON file

json_files=os.listdir(path)
f = open(os.path.join(path,'Data_KG_SI.POV.DDAY_page_1.json'))
# returns JSON object as 
# a dictionary
data = json.load(f)

